import Head from "next/head";
import dynamic from "next/dynamic";
import { useInView } from "react-intersection-observer";
import { isBrowser } from "../utils";

import { Header } from "@/components/Header/Header";
import { Hero } from "@/components/Hero/Hero";
import { About } from "@/components/About/About";
import { Amenities } from "@/components/Amenities/Amenities";
// import { useElementOnScreen } from "@/hooks/useElementOnScreen";
// import { Map } from "@/components/Map/Map";

const Map = dynamic(
  () => import("../components/Map/Map").then((mod) => mod.Map),
  {
    ssr: false,
  }
);

export default function Home() {
  const { ref, inView } = useInView({
    threshold: 0.09,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Header isAboutInView={inView} />
        <main>
          <Hero ref={ref} />
          <About />
          <Amenities />
          {isBrowser && <Map />}
        </main>
      </div>
    </>
  );
}
